# Generated by Django 4.1.7 on 2023-03-01 03:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gpa", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="account_id",
            field=models.CharField(
                max_length=16,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(16)],
            ),
        ),
    ]
