# Generated by Django 4.1.7 on 2023-03-01 05:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gpa", "0002_alter_bankaccount_account_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="notes",
            field=models.TextField(null=True),
        ),
    ]
