# Generated by Django 4.1.7 on 2023-03-05 23:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gpa", "0004_gpauser_alter_bankaccount_user_delete_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bankaccount",
            old_name="account_id",
            new_name="account_num",
        ),
    ]
